### PR TITLE
Support for typescript 1.5

### PR DESCRIPTION
**Pull request by steve8708**
Problem with this is DefinitelyTyped registry still has type definitions only for compiler version 0.4.0 (not yet 0.5.0 which this needs) so build will not pass :/

### CODE REVIEW

**Comment by steve8708** [comment]
Problem with this is DefinitelyTyped registry still has type definitions only for compiler version 0.4.0 (not yet 0.5.0 which this needs) so build will not pass :(

**Comment by steve8708** [comment]
I started submitting some experimental updates to my fork of this library with some ugly commits so I'm closing my PR :)

**Comment by pspeter3** [comment]
Ok, are you going to send a second pull request when they are ready?

**Comment by steve8708** [comment]
if you'd be interested I can send a PR when things seem fully ironed out and look good. since I didn't get a response on this one figured you may not be interested, but if you are just let me know :) 

note that I've added a few other things - like using a local tsconfig.json for compiler settings if found

**Comment by pspeter3** [comment]
This all sounds awesome! I'm definitely interested. Please send me a PR when you have it working :smile:

**Pull request closed without merging**
